<table width="100%"  border=0 cellspacing=0 cellpadding=0 align=center>
	<tr><td><img src="effects/corner1.gif" border=0 width=13></td>
		<td colspan=5 bgcolor=#DDC7FF></td>
		<td width=13 ><img src="effects/corner2.gif" border=0 width=13></td>
	</tr>
	<tr><td width=13 bgcolor=#DDC7FF></td>
		<td width=130 bgcolor=#E0D0FF valign=top>
				<table border=0 width=130 height=100%>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=upmenuitem href="index.htm">
						Artist</a>
				</td></tr>
				<tr><td height=1 bgcolor=#DDC7FF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=upmenuitem href="drummer/index.htm">
						Drummer</a>
				</td></tr>
			</table></td>
		<td width=13 bgcolor=#DDC7FF></td>
		<td bgcolor=#DDC7FF></td>
		<td align=left valign=center bgcolor=#DDC7FF>
				<a class=title1 href="index.htm">
				&nbsp;Katrina M. Fairbank</a></td>
		<td bgcolor=#DDC7FF valign=center align=center>
			<font face="maiandra gd, Arial, Helvetica, sans-serif" size=3 color=#773366>
				Southport, NC<br>
				910-540-4695<br>
				<a href=mailto:mail@kmfairbank.com>mail@kmfairbank.com</a>
			</font></td>
		<td width=13 bgcolor=#DDC7FF></td>
	</tr>
	<tr><td bgcolor=#DDC7FF colspan=6></td>
		<td><img src="effects/corner3.gif" border=0 width=13></td>
	</tr>
	<tr><td width=13 bgcolor=#DDC7FF></td>
		<td width=130 bgcolor=#E0D0FF valign=top>
			<table border=0 cellspacing=0 cellpadding=0 width=130 height=100%>
				<tr><td height=15 bgcolor=#DDC7FF></td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="bio.htm">
						Artist Bio</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
						<a class=menuitem href="artwork.htm">
							Artwork</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="galleries.htm">
						Galleries</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="commissions.htm">
						Commissions</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="prints.htm">
						Prints</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="shows.htm">
						Shows</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="awards.htm">
						Awards</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="friends.htm">
						Friends</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF height=30>
					<a class=menuitem href="mailto:mail@kmfairbank.com">
						Contact</a>
				</td></tr>
				<tr><td height=1 bgcolor=#FFFFFF></td></tr>
				<tr><td align=center valign=center bgcolor=#E0D0FF>
					<br><br><br><br><br><br><br><br><br>
				</td></tr>
			</table>
		</td>
		<td width=13 bgcolor=#DDC7FF></td>
		<td valign=top><img src="effects/incorner2.gif" border=0 width=13></td>
		<td colspan=2>
			<table width=100% border=0 cellspacing=0 cellpadding=30>
				<!-- Content goes here:  -->
				<tr><td><font face="maiandra gd, helvetica, sans serif" size=3 color=#000033>
				
<!-- Page content would show up here, after the include of pagestart.inc -->


<!-- Include pagestop.inc after -->